# Enhanced Slack message formatting for Cloud Run integration

def format_slack_message(summary_text, data_end_date, run_id, facts_json=None):
    """
    Format AI summary for Slack with rich formatting and structure
    """
    
    # Extract key metrics from facts_json if available
    metrics_section = ""
    if facts_json:
        try:
            import json
            facts = json.loads(facts_json) if isinstance(facts_json, str) else facts_json
            if facts:
                metrics_section = "\n📊 *Key Metrics:*\n"
                for key, value in facts.items():
                    # Format metric names nicely
                    formatted_key = key.replace('_', ' ').title()
                    metrics_section += f"• {formatted_key}: `{value}`\n"
        except:
            pass
    
    # Format the main message
    message = f"""🚀 *Ecommerce Analytics Summary* 
📅 *Period:* Data as of {data_end_date}
🆔 *Run ID:* `{run_id}`

📝 *AI Analysis:*
{summary_text}
{metrics_section}
🤖 *Generated by:* Vertex AI Gemini 2.0 Flash
⏰ *Timestamp:* <!date^{int(__import__('time').time())}^{{date_short_pretty}} at {{time}}|{__import__('datetime').datetime.now().isoformat()}>

---
📊 View full dashboard: https://your-evidence-dashboard.com
"""
    
    return message

def format_error_message(error_details, run_id):
    """Format error notifications for Slack"""
    return f"""⚠️ *Analytics Pipeline Alert*
🆔 *Run ID:* `{run_id}`
❌ *Status:* Failed

*Error Details:*
```
{error_details}
```

🔧 *Action Required:* Check Cloud Run logs for details
📊 Dashboard: https://console.cloud.google.com/run/jobs
"""

# Slack message blocks for rich formatting (optional advanced feature)
def create_slack_blocks(summary_text, data_end_date, run_id, facts_json=None):
    """
    Create Slack Block Kit formatted message for richer UI
    """
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": "🚀 Ecommerce Analytics Summary"
            }
        },
        {
            "type": "section",
            "fields": [
                {"type": "mrkdwn", "text": f"*📅 Period:*\n{data_end_date}"},
                {"type": "mrkdwn", "text": f"*🆔 Run ID:*\n`{run_id}`"}
            ]
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*📝 AI Analysis:*\n{summary_text}"
            }
        }
    ]
    
    # Add metrics section if available
    if facts_json:
        try:
            import json
            facts = json.loads(facts_json) if isinstance(facts_json, str) else facts_json
            if facts:
                metrics_text = ""
                for key, value in facts.items():
                    formatted_key = key.replace('_', ' ').title()
                    metrics_text += f"• {formatted_key}: `{value}`\n"
                
                blocks.append({
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"*📊 Key Metrics:*\n{metrics_text}"
                    }
                })
        except:
            pass
    
    # Add footer
    blocks.append({
        "type": "context",
        "elements": [
            {
                "type": "mrkdwn",
                "text": "🤖 Generated by Vertex AI Gemini 2.0 Flash | 📊 <https://your-dashboard.com|View Dashboard>"
            }
        ]
    })
    
    return blocks